### PR TITLE
Prepare v0.14.0 release

### PR DESCRIPTION
**Pull request by MikeGoldsmith**
Prepares the v0.14.0 release. This release doesn't include any functional changes, but does update the `VERSION` file and `CHANGELOG` that had been missed in previous releases.

### CODE REVIEW

**Comment by lizthegrey** [comment]
https://github.com/honeycombio/opentelemetry-exporter-go/blob/main/honeycomb/honeycomb.go#L403 update this file too

**Comment by lizthegrey** [comment]
go.mod changes to update otel-go SDK to v0.14?

**Comment by MikeGoldsmith** [comment]
I'll do the otel v0.14.0 update in a separate PR and update this PR once ready.

**Comment by MikeGoldsmith** [comment]
PR to update otel SDK to v0.14.0: https://github.com/honeycombio/opentelemetry-exporter-go/pull/98

**Review by paulosman — APPROVED** [review]

**Pull request merged**
